name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      param2:
        type: string
        description: sample param 2
        required: false
        default: "value 2"
    secrets:
      secret1: 
        required: true
    outputs:
      result:
        description: Result of this workflow
        value: ${{ jobs.deploy.output.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/download-artifact@v4
      with:
        #name: dist-file # it works but u have to be sure upper script uplod this.
        name: ${{ inputs.param2 }}
    - name: List files
      run: ls
    - name: Some text
      run: echo "Dummy output"
    - name: Set result output
      id: set-result
      run: echo "::set-output name=step-result::success"
